### ISSUE TITLE
Like to add Digital marketing sources

### ISSUE THREAD

**Issue by Alidhuniya** [debrajhyper/Topic_Learning_Resources#156]

**Comment by Alidhuniya** [comment]
> Thanks for opening your first issue here! **Say Hi on** [Twitter](https://twitter.com/debraj_010) 👋 [![Twitter FOLLOW](https://camo.githubusercontent.com/5eab07bdb567e291e945bad68607d4c115200752d89587b1400fb26f351c7d06/68747470733a2f2f696d672e736869656c64732e696f2f747769747465722f75726c2f68747470732f747769747465722e636f6d2f64656272616a5f3031302e7376673f7374796c653d736f6369616c266c6162656c3d466f6c6c6f77)](https://twitter.com/debraj_010)  [![LinkedIn URL](https://camo.githubusercontent.com/924599f18a551b36cb15b9481bfc070e6b41f685d9d81f7d966449259e1b2002/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f436f6e6e6563742d2532333030373742352e7376673f6c6f676f3d6c696e6b6564696e267374796c653d736f6369616c6c6162656c3d436f6e6e656374)](https://www.linkedin.com/in/debrajkarmakar010/)

please look at pr

**Comment by debrajhyper** [comment]
Thanks for your contributions. ❤
