### ISSUE TITLE
Add MDN docs as a learning resource for JavaScript

### ISSUE THREAD

**Issue by tinniaru3005** [debrajhyper/Topic_Learning_Resources#191]
[JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript)
This is one of the best resources for learning JavaScript and can be added.

**Comment by tinniaru3005** [comment]
Hey @debrajhyper, can you please assign this issue to me if you think we can add it?

**Comment by debrajhyper** [comment]
sure @tinniaru3005
