### ISSUE TITLE
Add game websites to learn some tech stacks

### ISSUE THREAD

**Issue by queenish001** [debrajhyper/Topic_Learning_Resources#52]
Heya @debrajhyper 
I wanted to add some websites where people can learn tech stacks like JS, Python, SQL, etc. as a game. 
Should I add them to the Documentation section?

**Comment by TheInspiredConjurer** [comment]
Hey, can I add on some wesites to this as part of hactoberfest? Kindly assign me this issue.

**Comment by debrajhyper** [comment]
You are all good to go.
