### ISSUE TITLE
Adding frontend and Web 3.0 resources 

### ISSUE THREAD

**Issue by Manish5121** [debrajhyper/Topic_Learning_Resources#71]

**Comment by debrajhyper** [comment]
Hey, That's great now just make your PR to this repo.

**Comment by Manish5121** [comment]
hey @debrajhyper i've already made a pr but i'm getting this issue 
![2022-10-01 (3)](https://user-images.githubusercontent.com/94914243/193413081-0f84da0d-31a8-45e9-8eca-cff4f7604173.png)

**Comment by debrajhyper** [comment]
Hey @Manish5121, we just saw your merge conflict. 
Make sure your repo is up-to-date with main branch then make the changes and add PR to the main repo.
